spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    devops01:
      url: jdbc:mysql://mysql.sinmn.cn:3306/devops-test?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2B8
      username: root
      password: mysql!@#root
      max-active: 1000
      initial-size: 1
      min-idle: 1
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      filters: config,stat,wall,slf4j
      validation-query: select 1
      test-while-idle: true
      test-on-borrow: true
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 50
      max-pool-prepared-statement-per-connection-size: 20
    devops02:
      url: jdbc:mysql://mysql.sinmn.cn:3306/xy-test?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2B8
      username: root
      password: mysql!@#root
      max-active: 1000
      initial-size: 1
      min-idle: 1
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      filters: config,stat,wall,slf4j
      validation-query: select 1
      test-while-idle: true
      test-on-borrow: true
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 50
      max-pool-prepared-statement-per-connection-size: 20
  #Redis服务器（IP）
  redis:
    host: redis.sinmn.cn
    #Redis服务端口号
    port: 6379
    password: redis!@#root
    #Redis服务器连接超时的时间（0代表不超时）
    timeout: 0
    #在borrow一个jedis实例时，是否提前进行validate操作；如果为true，则得到的jedis实例均是可用的
    test-on-borrow: true
    #连接超时时是否阻塞，false时报异常,ture阻塞直到超时, 默认true
    block-when-exhausted: true
    nodes:
    lettuce:
      pool:
        max-wait: 4  # 连接池最大阻塞等待时间（使用负值表示没有限制）
        min-idle: 1 # 连接池中的最小空闲连接
        max-idle: 10 # 连接池中的最大空闲连
        max-active: 200 # 连接池最大连接数
        max-total: 200 # 最大空连接数

debug: true
